# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaDoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Início')),
            ],
            options={
                'verbose_name_plural': 'Campanhas de Doação',
                'ordering': ['-data_inicio'],
                'verbose_name': 'Campanha de Doação',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateField(verbose_name='Data Requisição')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
            ],
            options={
                'verbose_name_plural': 'Obras',
                'ordering': ['titulo'],
                'verbose_name': 'Obra',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(verbose_name='Data Início')),
                ('status_pedido', models.CharField(choices=[('DT', 'Deferido totalmente'), ('I', 'Indeferido'), ('DP', 'Deferido parcialmente')], max_length=1, verbose_name='Esfera Federação')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CampanhaDoacao', verbose_name='Campanha de Doação')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido', verbose_name='Item do pedido'),
        ),
    ]
