# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arquivoexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoexcel',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='arquivoexcel',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
